### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by hackablemeister** [dronebird/DIDinJapan#1]
北海道
https://gist.github.com/hackablemeister/beb96ef2b10f4fc6aed0

**Comment by mapconcierge** [comment]
＞ @hackablemeister 
Thanks!! :-)

**Comment by hackablemeister** [comment]
青森県
https://gist.github.com/hackablemeister/46f60193eae7de7d3c06
岩手県
https://gist.github.com/hackablemeister/8fea20e9623ec36c023b
宮城県
https://gist.github.com/hackablemeister/a342aedfc5aff73136d1

**Comment by mapconcierge** [comment]
ありがとう！！ ＞ @hackablemeister 

![2015-12-10 13 01 18](https://cloud.githubusercontent.com/assets/416977/11706678/2c1aa090-9f3e-11e5-8961-30739f55465c.png)

**Comment by mapconcierge** [comment]
＞ @hackablemeister 
残念！ エンコードエラー

宮城県
https://gist.github.com/hackablemeister/a342aedfc5aff73136d1

![2015-12-10 13 09 50](https://cloud.githubusercontent.com/assets/416977/11706780/5c61e5d2-9f3f-11e5-811b-98e5e14a0f75.png)

**Comment by hackablemeister** [comment]
> @mapconcierge 
> あれま...もう一回直します

**Comment by hackablemeister** [comment]
宮城県【訂正版】
https://gist.github.com/hackablemeister/c953ae1628e5ca899178

秋田県
https://gist.github.com/hackablemeister/b07119c854e7a006d083

山形県
https://gist.github.com/hackablemeister/36426219eecaae18274c

**Comment by mapconcierge** [comment]
Thanks!! ＞ @hackablemeister 
バッチリです！

![2015-12-10 18 00 44](https://cloud.githubusercontent.com/assets/416977/11711216/1afa7130-9f68-11e5-822f-177b8ebddb20.png)

**Comment by hackablemeister** [comment]
福島県
https://gist.github.com/hackablemeister/0e900b1b7e25897bf33f

栃木県
https://gist.github.com/hackablemeister/2bef68ece69c1a740ef3

群馬県
https://gist.github.com/hackablemeister/b4e31b33347a7b3c0893

埼玉県
https://gist.github.com/hackablemeister/a844121964e0902183cd

千葉県
https://gist.github.com/hackablemeister/fc92502939e27a7277e0

**Comment by hackablemeister** [comment]
新潟県
https://gist.github.com/hackablemeister/410176e0eb62818e4ce2

富山県
https://gist.github.com/hackablemeister/dc79f059b8b49095d249

石川県
https://gist.github.com/hackablemeister/4e97d0fd52d739d631a7

**Comment by hackablemeister** [comment]
山梨県
https://gist.github.com/hackablemeister/238fa29baf5e8f53f7e3

長野県
https://gist.github.com/hackablemeister/6260aad4ae358a598788

**Comment by hackablemeister** [comment]
岐阜県
https://gist.github.com/hackablemeister/5e633b56d9ac8d9a99af

静岡県
https://gist.github.com/hackablemeister/61439d01092fa5737f5b

**Comment by hackablemeister** [comment]
愛知県
https://gist.github.com/hackablemeister/f25d97949cb7460a8886

三重県
https://gist.github.com/hackablemeister/3bad6df566b27cd74148

滋賀県
https://gist.github.com/hackablemeister/b4558fabd1ff2906de22

**Comment by hackablemeister** [comment]
京都府
https://gist.github.com/hackablemeister/91e1e598d0ba324c8229

大阪府
https://gist.github.com/hackablemeister/e6846644c32ed5640351

奈良県　
https://gist.github.com/hackablemeister/66c7973eb685d3b476de

兵庫県
https://gist.github.com/hackablemeister/11d5a01620edae870a33

和歌山県
https://gist.github.com/hackablemeister/4834f60c6bf2f11f4b92

鳥取県
https://gist.github.com/hackablemeister/d4bc0740a234b9780e84

島根県
https://gist.github.com/hackablemeister/d46183db9851af115fe1

岡山県
https://gist.github.com/hackablemeister/0df53bf3da30b5b776cc

広島県
https://gist.github.com/hackablemeister/dad504f1954d463fb3b7

山口県
https://gist.github.com/hackablemeister/5c4e5310085d8ff3c4f3

徳島県
https://gist.github.com/hackablemeister/09f83a0ff3639440daef

**Comment by hackablemeister** [comment]
香川県
https://gist.github.com/hackablemeister/53f453379a9474426d92

**Comment by hackablemeister** [comment]
愛媛県
https://gist.github.com/hackablemeister/1f354e16b7378216a151

高知県
https://gist.github.com/hackablemeister/97dc3c5763d81baa1351

福岡県
https://gist.github.com/hackablemeister/69020e212fcce9ac9e03

佐賀県
https://gist.github.com/hackablemeister/248134c528aa1da7b878

長崎県
https://gist.github.com/hackablemeister/b06f55bfcc7e88008349

熊本県
https://gist.github.com/hackablemeister/41ac5f1344ae81414143

宮崎県
https://gist.github.com/hackablemeister/b9676300e33cbf2da855

鹿児島県
https://gist.github.com/hackablemeister/e5db606f4859a1e0f438

沖縄県
https://gist.github.com/hackablemeister/47be98ea5b26c5b14e66

**Comment by mapconcierge** [comment]
Thanks!! @hackablemeister

**Comment by mapconcierge** [comment]
作業完了したので Closed しました！！
@hiroko-mapconcierge  おつかれさまでした。＆ @wata909 さんも PullRequest ありがとうございました！

**Comment by mapconcierge** [comment]
＞ @hackablemeister 

例の ogr2ogr コマンドサンプルを @wata909 さんがメモしてくれたので共有します。パラメータ詳細はまたゼミで説明します。
https://github.com/dronebird/DIDinJapan/blob/master/GeoJSON/shp2geojson.txt
